Edit Content From Comment
Georges47/triviagoservice pull request #35
Opened 2023-09-01 15:44 UTC by M4rkos2002

2023-09-07 21:39 UTC, matigayito approved these changes

2023-09-12 21:51 UTC, Georges47 requested changes

2023-09-12 21:51 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/impl/CommentServiceImpl.java
> +           Comment comment = this.findById(id);
Al obtener el comentario, chequear que el id del usuario que lo creó, es igual al id del usuario que lo está intentando editar (obtener este id a partir de la JWT de la request).

2023-09-12 21:51 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/presentation/controller/CommentController.java
> +    public ResponseEntity<?> editContent(@PathVariable("id") Long id, @RequestBody JsonNode jsonNode){
Crear y utilizar un DTO específico para editar comentarios, en vez de utilizar la clase JsonNode

2023-09-15 20:06 UTC, merged

2023-09-16 01:06 UTC, M4rkos2002 commented
Necesito esta PR para terminar los Tests de Edit Comment