Adding author to Quiz
Georges47/triviagoservice pull request #57
Opened 2023-09-16 13:24 UTC by SantiGrimoldi

2023-09-17 15:32 UTC, Georges47 requested changes

2023-09-17 15:32 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/persistence/repository/CommentRepository.java
> +    List<Comment> findAllByAnsweredCommentId(Long answeredCommentId);
Este método no haría falta ya que este atributo (`answeredCommentId`) no haría falta en la entidad comentario (`Comment`), como dejé escrito en el respectivo comentario.

2023-09-17 15:32 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/presentation/dto/AuthorDto.java
> +
Saca los espacios extras que quedaron acá.

2023-09-17 15:32 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/presentation/dto/CommentResponseDTO.java
> +public class CommentResponseDTO {
Elimina este DTO, que los comentarios "hijos" utilicen también el CommentDTO, ya que sería todo igual solo que el atributo de `responses` sería una lista vacía.

2023-09-17 15:32 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/CommentService.java
> +    CommentDTO findCommentAndAnswers(Long id);
No haría falta crear ninguno de estos dos métodos, habría que modificar el método ya existente `findAllByQuizId`, modificando la lógica interna necesaria y haciendo que devuelva `List<CommentDTO>` en vez de `List<Comment>`.

Sería cuestión de obtener todos los comentarios que tengan el `quizId` correspondiente (los cuales ya incluirían sus respuestas por el cambio que mencioné en la entidad `Comment`, de agregar una lista `replies`) y mappearlos a `CommentDTO`s.

Se podría tener un método privado que se encargue del mappeo de `Comment` a `CommentDTO`. Se me ocurre que el método además de recibir la entidad `Comment` también puede tener un argumento que sea un `boolean includeReplies`, el cual si es `true` incluya las replies y si es `false` no incluya dicho campo (quede en `null`) o le agregue una lista vacía.

2023-09-17 15:32 UTC, Georges47 commented on src/test/java/com/austral/triviagoservice/commentTest/Responses.java
> +public class Responses {
El test lo podrías dejar a un lado por el momento y una vez que tengamos la funcionalidad lista, te encargas del test (aun cuando no se considera una buena práctica) como si fuera otro issue (con otro PR y así).

2023-09-22 19:34 UTC, SantiGrimoldi commented
Dimi ahi hice algunos cambios fijate si esta bien

2023-09-25 04:06 UTC, Georges47 requested changes

2023-09-25 04:06 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/impl/CommentServiceImpl.java
> +        List<Comment> comments = findAllByQuizId(QuizId);
La lógica de los métodos `findAllCommentsAndAnswersByQuiz` y `setCommentsAndRepliesToDto` está bien pero se puede refactorizar para optimizarla y que utilice un estilo más funcional, quedando de la siguiente manera:

```java
@Override
public List<CommentDTO> findAllCommentsAndAnswersByQuiz(Long QuizId) {
    return findAllByQuizId(QuizId)
            .stream()
            .filter(c -> c.getParentComment() == null)
            .map(this::entityToDto)
            .collect(Collectors.toList());
}
```
Con el `.filter(c -> c.getParentComment() == null)` nos aseguramos de obtener solo los comentarios padres.

```java
@SneakyThrows
private CommentDTO entityToDto(Comment comment) {
    return CommentDTO.builder()
            .id(comment.getId())
            .author(getAuthor(comment.getUserId()))
            .content(comment.getContent())
            .creationDate(comment.getCreationDateTime().toString())
            .responses(comment.getReplies().stream().map(this::entityToDto).collect(Collectors.toList()))
            .build();
}
```
Podemos renombrar el método `setCommentsAndRepliesToDto` a `entityToDto` y que se encargue únicamente de convertir las entidades a DTOs. También, el método `toDate` no haría falta al convertir de comentario a DTO.

2023-09-25 13:16 UTC, SantiGrimoldi commented on src/main/java/com/austral/triviagoservice/business/CommentService.java
> +    List<CommentDTO> findAllCommentsAndAnswersByQuiz(Long QuizId);
Dimi se lo puedo cambiar a findAllByQuiz pq findAllByQuizId es una funcion que ya existe y se usa

2023-09-25 13:46 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/CommentService.java
> +    List<CommentDTO> findAllCommentsAndAnswersByQuiz(Long QuizId);
Es verdad. Fijate igual que el método ya existente de `findAllByQuizId` se utiliza únicamente en el `CommentServiceImpl` y lo único que hace es `commentRepository.findByQuizId(quizId)`. Entonces:

- Elimina ese método (el `findAllByQuizId`)
- Renombra el `findAllCommentsAndAnswersByQuiz` a `findAllByQuizId`
- Donde se usaba el método `findAllByQuizId` antiguo sería cuestión de reemplazarlo por `commentRepository.findByQuizId(quizId)`

Si puedes también renombra el método `findByQuizId` del `CommentRepository` a `findAllByQuizId` para que se entienda mejor. Cualquier cosa dejas otro comentario por acá o me escribes.

2023-09-26 12:38 UTC, Georges47 requested changes

2023-09-26 12:38 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/impl/UserServiceImpl.java
> +        if (user == null) return null;
Eliminar esta línea (i`f (user == null) return null;`) ya que `user` nunca será `null` (si no existe el usuario saltará la excepción).

2023-09-26 12:38 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/impl/CommentServiceImpl.java
> +                .creationDate(toDate(comment.getCreationDateTime().toString()))
No utilices el método `toDate(...)`.

2023-09-26 12:38 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/impl/CommentServiceImpl.java
> +    private String toDate(String dateString) {
Eliminar el método `toDate(...)` junto con todos los imports que ya no se utilicen.

2023-09-26 13:20 UTC, merged