TRI 96 obtener información de usuario
Georges47/triviagoservice pull request #81
Opened 2023-10-16 03:48 UTC by M4rkos2002

2023-10-20 21:24 UTC, matigayito commented on src/main/java/com/austral/triviagoservice/presentation/controller/UserController.java
> +            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
El not found tendria que ser un 404

2023-10-24 12:39 UTC, Georges47 requested changes

2023-10-24 12:39 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/presentation/controller/UserController.java
> +    @GetMapping("/{user_id}")
Cambiar path variable `user_id` por `id`.

2023-10-24 12:39 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/presentation/dto/UserInfoDto.java
> +    List<QuizDto> savedQuizes;
Corregir typo, cambiar `savedQuizes` por `savedQuizzes`.

2023-10-24 12:39 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/presentation/dto/UserInfoDto.java
> +    public static UserInfoDto dto(User user){
Cambiemos el método estático `dto` por un constructor:
```java
public UserInfoDto(User user){
    this.firstName = user.getFirstName();
    this.lastName = user.getLastName();
    this.birthDate = user.getBirthDate();
    this.email = user.getEmail();
    this.savedQuizzes = user.getSavedQuizzes().stream().map(QuizDto::createDto).collect(Collectors.toList());
    this.createdQuizzes = user.getQuizzes().stream().map(QuizDto::createDto).collect(Collectors.toList());
    this.createdDate = user.getCreationDate();
}
```

2023-10-24 12:48 UTC, Georges47 commented
El contenido de este PR ya está contenido en el PR #82.

2023-10-24 12:48 UTC, closed without merging