Resolve Quizzes
Georges47/triviagoservice pull request #84
Opened 2023-10-17 14:42 UTC by SantiGrimoldi

2023-10-18 03:20 UTC, Georges47 requested changes

2023-10-18 03:20 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/presentation/controller/QuizResolutionController.java
> +    public ResponseEntity<QuizResolution> createQuizResolution(@RequestBody QuizResolutionDto quizResolutionDto) {
Catchear las posibles excepciones que pueden surgir:
```java
@PostMapping
public ResponseEntity<?> createQuizResolution(@RequestBody QuizResolutionDto quizResolutionDto) {
    try {
        QuizResolution quizResolution = quizResolutionService.createQuizResolution(quizResolutionDto);
        return ResponseEntity.ok(quizResolution);
    } catch(InvalidContentException e) {
        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
    } catch (NotFoundException e) {
        return new ResponseEntity<>(e.getMessage(), HttpStatus.NOT_FOUND);
    }
}
```

2023-10-20 13:54 UTC, SantiGrimoldi commented
Ahi aplique los cambios Dimi

2023-10-21 13:29 UTC, Georges47 approved these changes

2023-10-21 13:29 UTC, merged