TRI-109
Georges47/triviagoservice pull request #86
Opened 2023-10-19 21:58 UTC by FranManfredi

2023-10-19 22:27 UTC, matigayito requested changes

2023-10-19 22:27 UTC, matigayito commented on src/main/java/com/austral/triviagoservice/presentation/controller/UserController.java
> +    @DeleteMapping("/user/{userId}")
El mapping deberia ser "/{userId}"

2023-10-21 13:40 UTC, Georges47 requested changes

2023-10-21 13:40 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/UserService.java
> +    void deleteUser(Long userId) throws InvalidContentException;
Cambiar `InvalidContentException` por `UnauthorizedException`.

2023-10-21 13:40 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/impl/UserServiceImpl.java
> +    public void deleteUser(Long userId) throws InvalidContentException{
Cambiar `InvalidContentException` por `UnauthorizedException`.

2023-10-21 13:40 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/business/impl/UserServiceImpl.java
> +        if (user.getId().equals(userId)) {
Formatear el código, en vez de:
```java
if (user.getId().equals(userId)) {
    userRepository.deleteById(userId);
}
else{
    throw new UnauthorizedException("You can only delete your own account");
}
```
tener:
```java
if (user.getId().equals(userId)) {
    userRepository.deleteById(userId);
} else {
    throw new UnauthorizedException("You can only delete your own account");
}
```

2023-10-21 13:40 UTC, Georges47 commented on src/main/java/com/austral/triviagoservice/presentation/controller/UserController.java
> +        userService.deleteUser(userId);
Catchear y manejar acorde la excepción, quedaría algo así el método:
```java
@DeleteMapping("/{userId}")
public ResponseEntity<?> deleteUser(@PathVariable("userId") Long userId) {
    try {
        userService.deleteUser(userId);
        return new ResponseEntity<>(HttpStatus.OK);
    } catch (UnauthorizedException e) {
        return new ResponseEntity<>(HttpStatus.UNAUTHORIZED);
    }
}
```

2023-11-05 02:55 UTC, Georges47 approved these changes

2023-11-05 02:59 UTC, Georges47 approved these changes

2023-11-05 03:00 UTC, merged